# Generated by Django 4.2.2 on 2023-07-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0014_alter_detalle_boleta_id_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
