# Generated by Django 4.2.2 on 2023-07-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0015_vehiculo_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='stock',
        ),
    ]
